global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'envoy'
    scrape_interval: 5s
    metrics_path: /stats/prometheus
    static_configs:
      - targets: ['envoy:9901']