{
 "title": "MMv2 Grpc Server - Go",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "gRPC Method RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(grpc_method) (rate(grpc_server_started_total{job=\"plugin-grpc-server-metrics\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request / Minutes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(http_requests_total{job=\"plugin-grpc-server-metrics\"}[2m])/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GoRoutines Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"plugin-grpc-server-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}