{
 "title": "Node Resources and Envoy",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes)/(1024*1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes - node_filesystem_avail_bytes)/(1024*1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Envoy - Active Http2 Connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "envoy_http_downstream_cx_http2_active{envoy_http_conn_manager_prefix=\"ingress-springbootgrpclocal\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Envoy - Active Http2 Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    { "expr": "envoy_http2_streams_active", "legendFormat": "__auto" }
   ]
  }
 ]
}